### ISSUE TITLE
1.1.0版本 /contact-request 出错？

### ISSUE THREAD

**Issue by LemonPAKA** [gnuf0rce/debug-helper#12]
我输入的是/contact-request QQ群号 accept
![image](https://user-images.githubusercontent.com/17202894/140321921-fc3d65f4-5b81-43c1-bcc1-b63b71cbac82.png)

**Comment by cssxsh** [comment]
你可以看下 `data/debug-helper/DebugRequestEventData.yml` 里有没有保存事件信息

**Comment by cssxsh** [comment]
你可以看下 `data/debug-helper/DebugRequestEventData.yml` 里有没有保存事件信息

**Comment by cssxsh** [comment]
with 1.1.2

**Comment by Echoosx** [comment]
使用1.1.2版本 仍出现报错：
`出现错误 java.lang.IllegalArgumentException: 找不到事件`
但功能运行正常
![image](https://user-images.githubusercontent.com/22994765/140602306-7c499bb5-5e99-4542-8246-35deb73f02e9.png)

另外希望能补充一下readme中[accept] 和 [black]是布尔值的描述，如果使用了布尔值以外的值貌似会直接识别成false

非常感谢！
