### ISSUE TITLE
跪求大佬做一个进群审核功能

### ISSUE THREAD

**Issue by Echoosx** [gnuf0rce/debug-helper#13]
不知道大佬有没有时间给debug-helper加一个**进群审核**的功能
先简短描述一下：在机器人收到加群申请的留言或问答后，能通过某种匹配方式来匹配留言，匹配成功的就同意进群
这种机械的操作也更适合交给机器人去做，但是我没怎么找到类似的插件，只找到了这个[ShrBox/GroupAdministrator](https://github.com/ShrBox/GroupAdministrator)，可惜只能运行在Mirai-console 0.5.2上

然后说一下可能会在意的几个需求：
1. 适应“发送验证消息”和“回答进群问题” 两种使用场景
2. 匹配方式有精确、模糊或正则
3. 匹配不成功的处理有多种选择：
    - 拒绝进群
    - 放置不管（交由其他管理员处理）
    - 通知拥有者进行处理

如果能做的话就万分感谢了！

**Comment by cssxsh** [comment]
with https://mirai.mamoe.net/topic/475
仅作推荐
实际上进群审核本身不是我插件的功能，这个插件是用来测试机器人功能是否正常的

**Comment by Echoosx** [comment]
但是有点可惜，作者后面这两个功能还未实现
![image](https://user-images.githubusercontent.com/22994765/140606112-8f10c3fe-6aad-472c-8b32-d8f2793585c1.png)
而且这个前两个功能感觉有点打扰群内的成员

**Comment by cssxsh** [comment]
> 但是有点可惜，作者后面这两个功能还未实现 ![image](https://user-images.githubusercontent.com/22994765/140606112-8f10c3fe-6aad-472c-8b32-d8f2793585c1.png) 而且这个前两个功能感觉有点打扰群内的成员

那你应该到 https://github.com/mzdluo123/SimpleGroupAuth 提 issue
