### ISSUE TITLE
关于/recall 

### ISSUE THREAD

**Issue by zhou-hack** [gnuf0rce/debug-helper#15]
你好，这个插件的/recall是不是只能撤回我发送/recall的消息 而不能够撤回机器人上一条发送/其他人发送的消息呢 这个问题我困惑了很久了 希望尽快解答下

**Comment by cssxsh** [comment]
这个问题已经在七天前更新的 [1.1.15](https://github.com/gnuf0rce/debug-helper/releases/tag/v1.1.5) 中尝试修复。


另外 不要使用 `希望尽快解答下` 这种指令性的话去指挥开发者做什么。
