### ISSUE TITLE
每次启动都会全群广播，全群广播无法使用空格

### ISSUE THREAD

**Issue by Orisland** [gnuf0rce/debug-helper#2]
### 能否关闭启动时的全群进入广播
![image](https://user-images.githubusercontent.com/59354152/127642301-513a9b4b-2012-4de3-a72c-e83230902d40.png)
每次重启都会跳这个，就很尴尬……
![image](https://user-images.githubusercontent.com/59354152/127642346-5e12a79a-237d-4d50-88a8-df4b04619049.png)
几十个群直接炸了……

### 能否避免空格的识别
全群广播无法输入空格，也就是成句的英文一旦输入只有第一个单词。
![image](https://user-images.githubusercontent.com/59354152/127642521-ac330404-9655-4a05-a5ee-39a9221d6650.png)
![image](https://user-images.githubusercontent.com/59354152/127642532-f5a1e51a-81e2-4237-8e2d-c60c78997fea.png)

**Comment by cssxsh** [comment]
上线消息 可以配置例外群聊

https://github.com/gnuf0rce/debug-helper/blame/master/readme.md#L36

**Comment by Orisland** [comment]
> 上线消息 可以配置例外群聊
> 
> https://github.com/gnuf0rce/debug-helper/blame/master/readme.md#L36

可以指定一类吗，比如指定所以群不推送，或者改为推送一句话，这个卡片太大了。
如果该信息可以自定义就太好了。
一个一个群添加不太方便于动态的群管理。
顺带，有办法解决空格问题吗？这个问题导致所有的英文句子都失效了。
