### ISSUE TITLE
接受群申请后执行拒绝

### ISSUE THREAD

**Issue by Cicini** [gnuf0rce/debug-helper#5]
![-2b952c3644eaf5dd](https://user-images.githubusercontent.com/62730438/128624832-0d081608-c121-4d34-b592-c0e49e07e3ae.jpg)

![-2037b1bc0b6aa9ec](https://user-images.githubusercontent.com/62730438/128624810-e191bcca-295b-4f82-bf9d-af6cbe42438b.jpg)

版本为最新的release

**Comment by cssxsh** [comment]
accept 是Boolean 值，填 true 或者 false

**Comment by Cicini** [comment]
> accept 是Boolean 值，填 true 或者 false

该更新readme了（

**Comment by cssxsh** [comment]
> > accept 是Boolean 值，填 true 或者 false
> 
> 该更新readme了（

accept 本来标注的就是 参数而不是命令路径
