### ISSUE TITLE
如何关闭启动广播

### ISSUE THREAD

**Issue by Ghost826** [gnuf0rce/debug-helper#8]
开发者你好，在使用你开发的插件过程中，每次启动QQ都会向几十个群发送上线消息，此功能感觉没有太大的必要，因为有时候仅仅是下线维护。所以希望开发者可以做一个能够关闭上线消息的功能，谢谢。

**Comment by cssxsh** [comment]
https://github.com/gnuf0rce/debug-helper#online-exclude

**Comment by Ghost826** [comment]
主要是不知道这个权限应该如何设置，或者说是不知道在哪里设置，能给说一下吗，麻烦了。
